// Generated by LiveScript 1.2.0
var fs, request, url, ids, ret, fetch;
fs = require('fs');
request = require('request');
url = function(page){
  return "https://spreadsheets.google.com/feeds/list/1RiIPdwuzW7wjuSv4hrgAIxbjhntK6nDowmg99bvN8T0/" + page + "/public/values?alt=json";
};
ids = [1, 2, 3, 4, 5];
ret = [];
fetch = function(){
  var id;
  if (!ids.length) {
    fs.writeFileSync('data.json', JSON.stringify(ret));
    return;
  }
  id = ids.splice(0, 1);
  return request({
    url: url(id),
    method: 'GET'
  }, function(e, r, b){
    console.log(b);
    ret.push(JSON.parse(b));
    return setTimeout(function(){
      return fetch();
    }, 100);
  });
};
fetch();